spring:
  application:
    name: template
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/dimediary" # for local run
    username: dimediary # for local run
    password: xXkKqqoOa7aDi8PtFfBL
logging:
  level:
    root: WARN
    com.template.demo: ${LOG_LEVEL:DEBUG}

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers
