spring:
  application:
    name: dimediary
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
  datasource:
    url: "jdbc:derby:..\\DB;create=true" # for local run
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      schema: APP
logging:
  level:
    root: WARN
    com.dimediary: ${LOG_LEVEL:DEBUG}

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers
