openapi: "3.0.0"
info:
  version: 1.0.0
  title: DimeDiary API
  description: REST API for DimeDiary
paths:
  /transactions:
    get:
      summary: load transactions
      description: load transactions
      operationId: getTransactions
      tags:
        - Transaction
      parameters:
        - in: query
          name: dateFrom
          schema:
            type: string
            description: date in format yyyy-MM-dd
          required: true
          description: Load transactions from this date on
        - in: query
          name: dateUntil
          schema:
            type: string
            description: date in format yyyy-MM-dd
          required: true
          description: Load transactions until this date
        - in: query
          name: bankAccountId
          schema:
            type: string
            format: uuid
          required: false
          description: bank account name for which to load transaction - if not set transaction without a bank account will be received
      responses:
        "200":
          description: get all transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
    put:
      summary: save transaction
      description: save transaction
      operationId: saveTransaction
      tags:
        - Transaction
      requestBody:
        description: the transaction to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        "201":
          description: transaction saved succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /transactions/{transactionId}:
    delete:
      summary: delete transaction
      description: delete transaction
      operationId: deleteTransaction
      tags:
        - Transaction
      parameters:
        - in: path
          name: transactionId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the transaction to delete
      responses:
        "204":
          description: transaction succesfully deleted
  /continuousTransactions:
    put:
      summary: save continuous transaction
      description: save continuous transaction
      operationId: saveContinuousTransaction
      tags:
        - ContinuousTransaction
      requestBody:
        description: the continuous transaction to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContinuousTransaction'
      responses:
        "201":
          description: continuous transaction saved succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContinuousTransaction'
  /continuousTransactions/{continuousTransactionId}:
    get:
      summary: load continuous transactions
      description: load continuous transactions
      operationId: getContinuousTransaction
      tags:
        - ContinuousTransaction
      parameters:
        - in: path
          name: continuousTransactionId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the continuous transaction to get
      responses:
        "200":
          description: get continuous transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContinuousTransaction'
    delete:
      summary: delete continuous transaction
      description: delete continuous transaction
      operationId: deleteContinuousTransaction
      tags:
        - ContinuousTransaction
      parameters:
        - in: path
          name: continuousTransactionId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the continuous transaction to delete
      responses:
        "204":
          description: continuous transaction succesfully deleted
  /categories:
    get:
      summary: get all categories
      description: get all categories
      operationId: getCategories
      tags:
        - Category
      responses:
        "200":
          description: get all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    put:
      summary: saves a category
      description: saves a category
      operationId: saveCategory
      tags:
        - Category
      requestBody:
        description: category to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        "201":
          description: category succesfully saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /categories/{categoryId}:
    delete:
      summary: delete category
      description: delete category
      operationId: deleteCategory
      tags:
        - Category
      parameters:
        - in: path
          name: categoryId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the category to delete
      responses:
        "204":
          description: category succesfully deleted
  /bankAccountCategories:
    get:
      summary: get all bank account categories
      description: get all bank account categories
      operationId: getBankAccountCategories
      tags:
        - BankAccountCategory
      responses:
        "200":
          description: get all bank account categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccountCategory'
    put:
      summary: saves a bank account category
      description: saves a bank account category
      operationId: saveBankAccountCategory
      tags:
        - BankAccountCategory
      requestBody:
        description: bank account category to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccountCategory'
      responses:
        "201":
          description: bank account category succesfully saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccountCategory'
  /bankAccountCategories/{bankAccountCategoryId}:
    delete:
      summary: delete bank account category
      description: delete bank account category
      operationId: deleteBankAccountCategory
      tags:
        - BankAccountCategory
      parameters:
        - in: path
          name: bankAccountCategoryId
          schema:
            type: string
            format: uuid
          required: true
          description: name of the bank account category to delete
      responses:
        "204":
          description: bank account category succesfully deleted
  /bankAccounts:
    get:
      summary: get all bankaccounts
      description: get all bankaccounts
      operationId: getBankAccounts
      tags:
        - BankAccount
      responses:
        "200":
          description: get all bankaccounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccount'
    put:
      summary: saves a bankaccount
      description: saves a  newbankaccount
      operationId: saveBankAccount
      tags:
        - BankAccount
      requestBody:
        description: bankaccount to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'
      responses:
        "201":
          description: bankaccount succesfully saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
  /bankAccount/{bankAccountId}:
    get:
      summary: get bankaccount
      description: get bankaccount
      operationId: getBankAccount
      tags:
        - BankAccount
      parameters:
        - in: path
          name: bankAccountId
          schema:
            type: string
            format: uuid
          required: true
          description: name of the bank account to get
      responses:
        "200":
          description: get bankaccount
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
    delete:
      summary: delete bank account
      description: delete bank account
      operationId: deleteBankAccount
      tags:
        - BankAccount
      parameters:
        - in: path
          name: bankAccountId
          schema:
            type: string
            format: uuid
          required: true
          description: name of the bank account to delete
      responses:
        "204":
          description: bank account succesfully deleted
  /balances:
    get:
      summary: get balance
      description: get balance for date range and bank account
      operationId: getBalances
      tags:
        - Balance
      parameters:
        - in: query
          name: bankAccountId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the bankaccount to request the balance for
        - in: query
          name: dateFrom
          schema:
            type: string
            description: date in format yyyy-MM-dd
          required: true
          description: first date to receive the balance
        - in: query
          name: dateUntil
          schema:
            type: string
            description: date in format yyyy-MM-dd
          required: true
          description: end date to receive the balance
      responses:
        "200":
          description: get all balances for the given bankaccount between the dateFrom and dateUntil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Balance'
    post:
      summary: recreate balance histories
      description: recreate balance histories for given bank account
      operationId: recreateBalances
      tags:
        - Balance
      parameters:
        - in: query
          name: bankAccountId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the bankaccount for which the balances should be recreate
      responses:
        "204":
          description: balances succesfully recreate
components:
  schemas:
    Transaction:
      properties:
        id:
          type: string
          format: uuid
        subject:
          type: string
        amountEuroCent:
          type: integer
        date:
          type: string
          description: date in format yyyy-MM-dd
        bankAccount:
          $ref: '#/components/schemas/BankAccount'
        category:
          $ref: '#/components/schemas/Category'
        continuousTransaction:
          $ref: '#/components/schemas/ContinuousTransaction'
        fixCost:
          type: boolean
    ContinuousTransaction:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        amountEuroCent:
          type: integer
        dateBegin:
          type: string
          description: date in format yyyy-MM-dd
        bankAccount:
          $ref: '#/components/schemas/BankAccount'
        category:
          $ref: '#/components/schemas/Category'
        recurrenceRule:
          type: string
        fixCost:
          type: boolean
    BankAccount:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        bankName:
          type: string
        iban:
          type: string
          format: iban
        bic:
          type: string
          format: bic
        bankAccountCategory:
          $ref: '#/components/schemas/BankAccountCategory'
        dateStartBalance:
          type: string
          description: date in format yyyy-MM-dd
        startBalanceEuroCent:
          type: integer
    BankAccountCategory:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        isRealAccount:
          type: boolean
    Category:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        fixCost:
          type: boolean
    Balance:
      properties:
        bankAccountId:
          type: string
          format: uuid
        date:
          type: string
          description: date in format yyyy-MM-dd
        balanceEuroCent:
          type: integer
