openapi: "3.0.0"
info:
  version: 0.0.1
  title: Template API
  description: A simple API to post and receive likes 
paths:
  /transaction:
    get:
      summary: get all transactions
      description: get all transactions
      tags:
        - Transaction
      responses:
        "200":
          description: get all transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
components:
  schemas:
    Transaction:
      properties:
        uuid:
          type: string 
          format: uuid
        subject:
          type: string
        amount:
          type: integer
        date:
          type: string
    Transactions:
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
          
