/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.template.api;

import com.template.model.Like;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-03-01T14:50:47.791265800+01:00[Europe/Berlin]")

@Api(value = "Like", description = "the Like API")
public interface LikeApi {

    @ApiOperation(value = "get the number of **Like** in DB", nickname = "likeCountGet", notes = "get the number of likes in the the DB", response = Object.class, tags={ "Like", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Count updated", response = Object.class) })
    @RequestMapping(value = "/like/count",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<Object> likeCountGet();


    @ApiOperation(value = "Persists a **Like**", nickname = "likePost", notes = "Persists a **Like** in the the DB", response = Like.class, tags={ "Like", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Like created", response = Like.class) })
    @RequestMapping(value = "/like",
        produces = "application/json", 
        method = RequestMethod.POST)
    ResponseEntity<Like> likePost();

}
