/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.template.api;

import com.template.model.Transactions;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-05-30T23:00:08.164597+02:00[Europe/Berlin]")

@Api(value = "Transaction", description = "the Transaction API")
public interface TransactionApi {

    @ApiOperation(value = "get all transactions", nickname = "transactionGet", notes = "get all transactions", response = Transactions.class, tags={ "Transaction", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "get all transactions", response = Transactions.class) })
    @RequestMapping(value = "/transaction",
        produces = "application/json", 
        method = RequestMethod.GET)
    ResponseEntity<Transactions> transactionGet();

}
